script: make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: im3WtfaRYiADkIa8/Tl+ERsBrjB4qZzJAcqKz7oraQXfuFHx//6peDknz5NQMrQxkIN4izyGDFD7KVrU5uiJ8y4MlMxQRCyO1bWtSgUbXpC7jlv+Gf5ezVusM0YuYk2FcL3+dWPqfhJScQ9q2nch6wmwzfIfMqO7tVUvU/VN87o=
  app:
    develop: eva-presentation-functional01
